$:.unshift(File.dirname(__FILE__)) unless
  $:.include?(File.dirname(__FILE__)) || $:.include?(File.expand_path(File.dirname(__FILE__)))

require File.dirname(__FILE__) + '/phidgets.so'

require File.dirname(__FILE__) + '/phidgets/dictionary.rb'
require File.dirname(__FILE__) + '/phidgets/manager.rb'
require File.dirname(__FILE__) + '/phidgets/common.rb'
require File.dirname(__FILE__) + '/phidgets/accelerometer.rb'
require File.dirname(__FILE__) + '/phidgets/bldc_motor.rb'
require File.dirname(__FILE__) + '/phidgets/capacitive_touch.rb'
require File.dirname(__FILE__) + '/phidgets/current_input.rb'
require File.dirname(__FILE__) + '/phidgets/dc_motor.rb'
require File.dirname(__FILE__) + '/phidgets/dictionary.rb'
require File.dirname(__FILE__) + '/phidgets/digital_input.rb'
require File.dirname(__FILE__) + '/phidgets/digital_output.rb'
require File.dirname(__FILE__) + '/phidgets/distance_sensor.rb'
require File.dirname(__FILE__) + '/phidgets/encoder.rb'
require File.dirname(__FILE__) + '/phidgets/frequency_counter.rb'
require File.dirname(__FILE__) + '/phidgets/gps.rb'
require File.dirname(__FILE__) + '/phidgets/gyroscope.rb'
require File.dirname(__FILE__) + '/phidgets/humidity_sensor.rb'
require File.dirname(__FILE__) + '/phidgets/ir.rb'
require File.dirname(__FILE__) + '/phidgets/light_sensor.rb'
require File.dirname(__FILE__) + '/phidgets/magnetometer.rb'
require File.dirname(__FILE__) + '/phidgets/motor_position_controller.rb'
require File.dirname(__FILE__) + '/phidgets/ph_sensor.rb'
require File.dirname(__FILE__) + '/phidgets/pressure_sensor.rb'
require File.dirname(__FILE__) + '/phidgets/rfid.rb'
require File.dirname(__FILE__) + '/phidgets/rc_servo.rb'
require File.dirname(__FILE__) + '/phidgets/resistance_input.rb'
require File.dirname(__FILE__) + '/phidgets/sound_sensor.rb'
require File.dirname(__FILE__) + '/phidgets/spatial.rb'
require File.dirname(__FILE__) + '/phidgets/stepper.rb'
require File.dirname(__FILE__) + '/phidgets/temperature_sensor.rb'
require File.dirname(__FILE__) + '/phidgets/voltage_input.rb'
require File.dirname(__FILE__) + '/phidgets/voltage_output.rb'
require File.dirname(__FILE__) + '/phidgets/voltage_ratio_input.rb'

